### ISSUE TITLE
please add undo future

### ISSUE THREAD

**Issue by erolkaftanoglu** [aaronbond/SwipeDeck2#2]
This is only my request can you please add some function to add Undo support .
It will be like when i click on undo it will swap back last card which i have been swapped

**Comment by aaronbond** [comment]
no problem, i've got a plan to do that. i have some things on today but i'll take a look at adding it this evening (Australian time)

**Comment by aaronbond** [comment]
hey just want to let you know i haven't forgotten about this feature, i did a quick implementation and decided that to do it properly is worth investing a bit more time in.

i'm going to change some core parts of the code (mostly the deck object which is a listenable arraylist like collection, i will change it to be more like a listenable dequeue backed by a linked list)

**Comment by aaronbond** [comment]
i've got a public method in version 2.0.6 

public void unSwipeCard()

let me know how that goes for you. as of now it fades the last card in on top of the deck.

**Comment by Agreema** [comment]
If I remove the first item from the list like this - 

list.remove((int)topId);
adapter.notifyDataSetChanged();

and then I do unSwipeCard() on second card, then it loads second card on top of itself and then crashes on swipe.

What I want is. If I remove a card from list then do unswipe then it should skip the last card and load the card prior to it or if it was a first card then it should keep showing the current top card
