### ISSUE TITLE
SwipeDeckCallback is not attached to anything

### ISSUE THREAD

**Issue by lekz112** [aaronbond/SwipeDeck2#3]
Version - 2.0.3

While it's possible to set callback via setCallback(SwipeDeckCallback callback), it's never invoked. 
Judging by source code it's never used.
I assume it should be called inside anonymous callback passed to CardContainer:
https://github.com/aaronbond/SwipeDeck2/blob/master/swipedeck2/src/main/java/com/daprlabs/aaron/swipedeck2/SwipeDeck.java#L159

It's strange that this library was released with this kind of issue, are you sure it's ready to be used?
I also see that you have RxBus not attached to anything:
https://github.com/aaronbond/SwipeDeck2/blob/master/swipedeck2/src/main/java/com/daprlabs/aaron/swipedeck2/SwipeDeck.java#L32
As the result you have a RxJava dependency, that seems very strange for a UI-only lib.

**Comment by aaronbond** [comment]
yeah sorry about that, i'll make sure it's hooked up soon.

**Comment by lekz112** [comment]
I'd love to file pull-request for this, but I am utterly confused by the project structure.
What are swipedeck and swipedeck2?
It seems that swipedeck is the one updated recently, is that the actual source code?

**Comment by aaronbond** [comment]
this is the current project it's a re write. it would be trivial to hook up the callback, it's just the callback from the swipelistener. 

i've got a new version coming soon that should be easier to understand.

**Comment by aaronbond** [comment]
ok try 2.0.5. I've got quite a lot of changes to the code so hopefully it's all working for you.

**Comment by aaronbond** [comment]
and as for the confusing project structure, yes it even confuses me at times. a lot of it owes to me having to write and architect workarounds for some of the android quirks as i go.

hopefully this version is easier to understand.

**Comment by lekz112** [comment]
Thank you, now it's working as expected.
Btw, you forgot to tag it,
