### ISSUE TITLE
SwipeTopCardLeft/SwipeTopCardRight duration is ignored

### ISSUE THREAD

**Issue by lekz112** [aaronbond/SwipeDeck2#6]
It seems that you are using hard coded constant instead:
https://github.com/aaronbond/SwipeDeck2/blob/master/swipedeck/src/main/java/com/daprlabs/aaron/swipedeck/Utility/SwipeListener.java#L243

**Comment by aaronbond** [comment]
ah yes... well spotted. i'll fix that or just send me a pull request.
