### ISSUE TITLE
RxJava dependency

### ISSUE THREAD

**Issue by lekz112** [aaronbond/SwipeDeck2#7]
Right now this library have a compile dependency on : 'io.reactivex:rxjava' and 'io.reactivex:rxandroid':
https://github.com/aaronbond/SwipeDeck2/blob/master/swipedeck/build.gradle#L28

Why would this lib require them? The only place it's used is RxBus class:
https://github.com/aaronbond/SwipeDeck2/blob/master/swipedeck/src/main/java/com/daprlabs/aaron/swipedeck/Utility/RxBus.java
And it's not used anywhere

Please either remove them completely, or at least change them to "provided" scope.

**Comment by aaronbond** [comment]
mmm yeah i forgot to remove it, i was using it in a much earlier version of the library. i'll get on that or just make a pull
